<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Shop',
                'link' => 'shop',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 01:50:53',
                'updated_at' => '2026-01-02 01:59:50',
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Account',
                'link' => 'home',
                'parent' => 0,
                'sort' => 3,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 01:59:46',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Bamboo',
                'link' => '/shop?category=6',
                'parent' => 18,
                'sort' => 7,
                'class' => NULL,
                'menu' => 5,
                'depth' => 1,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 02:44:19',
                'updated_at' => '2026-01-05 07:43:29',
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Specialty',
                'link' => '/shop?category=9',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 02:44:44',
                'updated_at' => '2026-01-02 02:44:47',
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Supplies',
                'link' => '/shop?category=8',
                'parent' => 0,
                'sort' => 1,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 17:53:38',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            5 => 
            array (
                'id' => 6,
                'label' => '|',
                'link' => '#divider-h',
                'parent' => 0,
                'sort' => 7,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 1,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 22:03:58',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'Admin',
                'link' => 'admin',
                'parent' => 0,
                'sort' => 8,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 1,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-02 22:04:14',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'Shop',
                'link' => 'shop',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 2,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 00:49:46',
                'updated_at' => '2026-01-04 00:49:47',
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'Cart',
                'link' => 'cart',
                'parent' => 0,
                'sort' => 5,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 03:14:27',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'Checkout',
                'link' => 'checkout',
                'parent' => 9,
                'sort' => 6,
                'class' => NULL,
                'menu' => 1,
                'depth' => 1,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 03:14:53',
                'updated_at' => '2026-01-04 03:25:56',
            ),
            10 => 
            array (
                'id' => 11,
                'label' => '|',
                'link' => '#divider-h',
                'parent' => 0,
                'sort' => 4,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 03:15:37',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            11 => 
            array (
                'id' => 12,
                'label' => '|',
                'link' => '#divider-h',
                'parent' => 0,
                'sort' => 2,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 03:24:42',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Collections',
                'link' => '#',
                'parent' => 0,
                'sort' => 1,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-04 03:25:15',
                'updated_at' => '2026-01-04 03:25:21',
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'Flowering Plants',
                'link' => '/shop?category=14',
                'parent' => 0,
                'sort' => 2,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:42:45',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'Foliage Plants',
                'link' => '/shop?category=13',
                'parent' => 0,
                'sort' => 3,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:42:49',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            15 => 
            array (
                'id' => 16,
                'label' => 'Outdoor Plants',
                'link' => '/shop?category=15',
                'parent' => 0,
                'sort' => 4,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:42:55',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            16 => 
            array (
                'id' => 17,
                'label' => 'Succulents',
                'link' => '/shop?category=12',
                'parent' => 0,
                'sort' => 5,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:43:07',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            17 => 
            array (
                'id' => 18,
                'label' => 'Planters',
                'link' => '/shop?category=19',
                'parent' => 0,
                'sort' => 6,
                'class' => NULL,
                'menu' => 5,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:43:15',
                'updated_at' => '2026-01-05 07:43:21',
            ),
            18 => 
            array (
                'id' => 19,
                'label' => 'Ceramics',
                'link' => '/shop?category=17',
                'parent' => 18,
                'sort' => 8,
                'class' => NULL,
                'menu' => 5,
                'depth' => 1,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 07:43:25',
                'updated_at' => '2026-01-05 07:43:31',
            ),
            19 => 
            array (
                'id' => 20,
                'label' => 'Flowering Plants',
                'link' => '/shop?category=34',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:31:56',
                'updated_at' => '2026-01-05 08:34:58',
            ),
            20 => 
            array (
                'id' => 21,
                'label' => 'Foliage Plants',
                'link' => '/shop?category=33',
                'parent' => 0,
                'sort' => 1,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:32:01',
                'updated_at' => '2026-01-05 08:34:58',
            ),
            21 => 
            array (
                'id' => 22,
                'label' => 'Outdoor Plants',
                'link' => '/shop?category=35',
                'parent' => 0,
                'sort' => 2,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:32:07',
                'updated_at' => '2026-01-05 08:34:58',
            ),
            22 => 
            array (
                'id' => 23,
                'label' => 'Tropical Plants',
                'link' => '/shop?category=31',
                'parent' => 0,
                'sort' => 3,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:32:12',
                'updated_at' => '2026-01-05 08:34:58',
            ),
            23 => 
            array (
                'id' => 24,
                'label' => 'Succulents',
                'link' => '/shop?category=32',
                'parent' => 0,
                'sort' => 4,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:32:19',
                'updated_at' => '2026-01-05 08:34:58',
            ),
            24 => 
            array (
                'id' => 25,
                'label' => 'Planters',
                'link' => '/shop?category=39',
                'parent' => 0,
                'sort' => 5,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'role_id' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
                'created_at' => '2026-01-05 08:32:24',
                'updated_at' => '2026-01-05 08:34:58',
            ),
        ));
        
        
    }
}